#!/usr/bin/env node
/**
 * Build script – generates static/config.js from environment variables.
 * Used by both Vercel (vercel.json buildCommand) and GitHub Actions (CI step).
 *
 * Required env vars: SUPABASE_URL, SUPABASE_ANON_KEY
 */

const fs   = require('fs');
const path = require('path');

const url = process.env.SUPABASE_URL      || '';
const key = process.env.SUPABASE_ANON_KEY || '';

if (!url || !key) {
    console.warn('⚠️  SUPABASE_URL or SUPABASE_ANON_KEY not set — config.js will have empty credentials');
}

const content = `// Auto-generated by build.js — do not edit manually
const SUPABASE_URL      = '${url}';
const SUPABASE_ANON_KEY = '${key}';
window.DEBUG_MODE = false;

(function initializeSupabase() {
    if (typeof supabase === 'undefined') {
        console.error('❌ Supabase library not loaded.');
        return;
    }

    if (!SUPABASE_URL || !SUPABASE_ANON_KEY ||
        SUPABASE_URL === 'YOUR_SUPABASE_URL') {
        console.error('⚠️ Supabase credentials not configured.');
        const banner = document.getElementById('error-banner');
        const msg    = document.getElementById('error-banner-message');
        if (banner && msg) {
            msg.textContent = 'Database not configured. Please set up config.js with your Supabase credentials.';
            banner.classList.remove('hidden');
        }
        return;
    }

    try {
        const { createClient } = supabase;
        window.supabaseClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
        console.log('✅ Supabase client initialized');
    } catch (error) {
        console.error('❌ Failed to initialize Supabase client:', error);
    }
})();
`;

const outPath = path.join(__dirname, 'static', 'config.js');
fs.writeFileSync(outPath, content, 'utf8');
console.log('✅ config.js written to', outPath);
